AWSTemplateFormatVersion: "2010-09-09"
Resources:
  InstWindows:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref IamProfileWindowsServer
      ImageId: !Ref Image
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetID
      Tags:
        - Key: Name
          Value: !Ref InstanceName
        - Key: SSM_Association
          Value: !Sub windows-${Environment}
  IamProfileWindowsServer:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - !Ref IamRoleWindowsServer
      InstanceProfileName: WindowsServer
  IamRoleWindowsServer: 
    Type: "AWS::IAM::Role"
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      RoleName: !Sub "Role=CMTPoolServer,Env=${Environment},Service=EC2,Rights=RW"
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      Policies:
      - PolicyName: !Sub "Role=WindowsServer,Env=${Environment},Service=Cloudwatch,Rights=RW"
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - logs:PutLogEvents
            Resource: "*"
Parameters:
  InstanceType:
    Type: String
    Description: EC2 instance type
    Default: m5a.large
    AllowedValues:
      - m5a.large
  Image:
    Type: String
    Default: ami-07a29e78aeb420471
    AllowedValues:
      - ami-07a29e78aeb420471
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
  Account:
    Type: String
    Default: sandbox
    AllowedValues:
      - sandbox
  SubnetID:
    Type: String
    Description: SubnetID
    Default: subnet-407ed619 #shared services staging
    AllowedPattern: 'subnet-[0-9a-f]*'
  InstanceName:
    Type: String
    Description: The name of the instance
    Default: anewwindowsserver
  KeyName:
      Type: String
      Description: aws secret key for this instance
      Default: bolson-sandbox
